server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jcskqqv7t72fqlv0.us.auth0.com/

  main:
    allow-bean-definition-overriding: true

auth0:
  audience: http://localhost:8888