server:
  port: 7200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FT-USER-DB

auth:
  audience: http://localhost:7200

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jcskqqv7t72fqlv0.us.auth0.com/
          jwk-uri: https://dev-jcskqqv7t72fqlv0.us.auth0.com/.well-known/jwks.json



management:
  endpoints:
    web:
      exposure:
        include: "*"