server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FT-VIDEO-DB

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jcskqqv7t72fqlv0.us.auth0.com/

      google:
        clientId: 650415461249-a00l045u388caglnreersa8oq59jomk0.apps.googleusercontent.com
        secretKey: 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

auth0:
  audience: http://localhost:7100
  user-info-endpoint: https://dev-jcskqqv7t72fqlv0.us.auth0.com/userinfo


management:
  endpoints:
    web:
      exposure:
        include: "*"

video:
  storage:
    local:
      directory: E:\I-TUBE\front-free-tube\src\assets

