server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FT-VIDEO-DB

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

video:
  storage:
    local:
      directory: D://IXML//tube-storage

