server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FT-VIDEO-DB

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fujichanel.eu.auth0.com/

auth0:
  audience: http://localhost:7100/


management:
  endpoints:
    web:
      exposure:
        include: "*"

video:
  storage:
    local:
      directory: E:\I-TUBE\front-free-tube\src\assets

