server:
  port: 7100

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FT-VIDEO-DB

management:
  endpoints:
    web:
      exposure:
        include: "*"

video:
  storage:
    local:
      directory: D://IXML//tube-storage

